### ISSUE TITLE
website title no see ?

### ISSUE THREAD

**Issue by jun-lu** [bobbywalters/wikiwp#1]
我刚装好主题title是正常的，但是不知道这后台设置了什么东西，title不能正常显示了。
不知道为什么？

website: www.80wo.com

header.php

```

<title><?php wp_title( '|', true, 'right' ); ?></title>

```

**Comment by bobbywalters** [comment]
It looks like the original authors are now posting theme updates to https://wordpress.org/themes/wikiwp/ since the version is now _1.5.06_. The changes I've made here in this fork are at version _1.3_ which has a completely different look and feel. If you have upgraded then the themes `functions.php` was overridden which did have a filter to add the blog name to the title using the `wp_title` filter.

With that said, to get the functionality that exists in this fork for the title add this block of code to your `functions.php` file:

``` php
function wikiwp_title($title, $sep, $seplocation) {
    if (empty($title)) {
        return get_bloginfo('name');
    }

    if ('right' == $seplocation) {
        return $title . get_bloginfo('name');
    }

    return get_bloginfo('name') . $title;
}
add_filter('wp_title', 'wikiwp_title', 10, 3);
```

**Note**: Please be aware that if you update the theme, the update process will override these changes and you'd have to add them back again after the update finished.

**Comment by jun-lu** [comment]
Thanks ,非常感谢你的答复，按照你的方法问题解决了
